### ISSUE TITLE
"Research papers" section is mis-rendered sometimes

### ISSUE THREAD

**Issue by al42and** [codeplaysoftware/sycl.tech-content#21]
Currently, the website only properly renders the list of authors when they are represented as plain strings:

```
authors:
  - Alice
  - Bob
```

But [some](https://github.com/codeplaysoftware/sycl.tech-content/blob/main/content/research_papers/2024/2024-04-16-enabling-performance-portability-on-the-ligen-drug-discovery-pipeline.md) papers have a dictionary there:

```
authors:
  - name: Alice
  - name: Bob
```

And those are not rendered properly:

![image](https://github.com/user-attachments/assets/b2eca239-946d-4b86-9f69-a7489b3d4b25)

**Comment by scottstraughan** [comment]
Yup, thats a bug - good find!
